### ISSUE TITLE
jsonlines usage

### ISSUE THREAD

**Issue by VasssilPopov** [VasssilPopov/AllSpiders#6]
How to use it?
- what is file extension for reports still *.json  or *.jl or *. jsonlines  or something else 

So the call spider execution will be:  
scrapy runspider -o  Mediapool2017-05-10.js  -t jsonlines

**Comment by peio** [comment]
It is still .json. This is why in the read_json fucntion, we check what the format is and read it accordingly: https://github.com/VasssilPopov/AllSpiders/blob/master/_LIBRARY/ScrapingHelpers.py#L11
